//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyncSample
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    
    public partial class CallHistory
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string CallFrom { get; set; }
        public string CallTo { get; set; }
        public bool IsIntern { get; set; }
    }
}
